name: Push DOCS

on:
  push:

jobs:
  deploy:
    name: Deploy to github pages
    runs-on: ubuntu-20.04
    container: lkrisz1911/doxy_image:latest
    steps:
    - uses: actions/checkout@master
    - run: make Generate_documentation

    - name: Push git subdir as branch
      uses: s0/git-publish-subdir-action@v2.4.0

    env:
      REPO: self
      BRANCH: gh-pages
      FOLDER: DOCS/html
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}