  
name: Parser Tests
on: push
jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install libgtest-dev && sudo apt install -y gcc g++ && sudo apt install cmake && cd /usr/src/gtest && sudo cmake . && sudo make  && sudo cp *.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
      - name: Run cmake
        run: cd tests && cmake . && make
      - name: Run parser tests
        run: cd tests && ./runTests