  
name: Unit tests
on: push
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: make Install_googletest_and_cmake
      - name: cmake
        run: make Make_tests_with_cmake
      - name: Run parser tests
        run: make Run_parsertest
      - name: Run unit tests
        run: make Run_unittests
