  
name: Parser Tests
on: push
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: make Install_googletest_and_cmake
      - name: cmake
        run: make Make_parsertests_with_cmake
      - name: Run Tests
        run: make Run_parsertest