name: Build test, static code analysis, memory check

on:
  push

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: make Install_all_dependencies
      - name: Cppcheck code analysis
        run: make Static_code_analysis_cppcheck
      - name: Upload Cppcheck result 
        uses: actions/upload-artifact@v2  
        with:
          name: cppcheck_results
          path: cppcheck_results.txt
      - name: Build
        run: make build
      - name: Valgrind check
        run: make Valgrind
      - name: In-out tests
        run: make In-out_tests