name: Build test, static code analysis, memory check

on:
  push

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    container: lkrisz1911/test_image:latest
    steps:
      - uses: actions/checkout@v2
      - name: Cppcheck code analysis
        run: make Static_code_analysis_cppcheck
      - name: Upload Cppcheck result 
        uses: actions/upload-artifact@v2  
        with:
          name: cppcheck_results
          path: cppcheck_results.txt
      - name: Build
        run: make build
      - name: Memory leak check
        run: make Memcheck
      - name: Upload valgrind results
        uses: actions/upload-artifact@v2  
        with:
          name: valgrind_log
          path: valgrind_log.txt
      - name: In-out tests
        run: make In-out_tests
      - name: Upload results of test
        uses: actions/upload-artifact@v2  
        with:
          name: output_test
          path: output_test.txt